[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

[dependencies]
volatile = "0.1.0"
spin = "0.5.2"


[lib]
crate-type=["staticlib"]


[profile.dev]
panic="abort"

[profile.release]
panic="abort"